from __future__ import annotations

import asyncio
import hashlib
import logging
import re
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
)
from langchain_core.chat_history import BaseChatMessageHistory
from pydantic import BaseModel, Field

from server.models.interfaces import BaseLLMConfigurationInterface
from server.helpers import get_config
from server.models.enums import LLMProvider, LLMExecutionMode

from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_anthropic import ChatAnthropic
from langchain_cohere import ChatCohere
from langchain_ollama import ChatOllama

logger = logging.getLogger(__name__)


# ================================================================
# SECTION 1 — TOKEN BUDGET
# ================================================================

@dataclass
class TokenBudget:
    total_context:    int   = 8192
    system_reserve:   int   = 512
    response_reserve: int   = 1024
    summary_max:      int   = 600
    user_turn_max:    int   = 800
    hot_buffer_pct:   float = 0.45

    @property
    def available(self) -> int:
        return (self.total_context
                - self.system_reserve
                - self.response_reserve
                - self.summary_max
                - self.user_turn_max)

    @property
    def hot_budget(self) -> int:
        return max(400, int(self.available * self.hot_buffer_pct))

    @classmethod
    def for_local(cls, context_window: int = 8192) -> "TokenBudget":
        return cls(
            total_context=context_window,
            system_reserve=400,
            response_reserve=1024,
            summary_max=400,
            user_turn_max=600,
            hot_buffer_pct=0.40,
        )

    @classmethod
    def for_remote(cls, context_window: int = 128000) -> "TokenBudget":
        return cls(
            total_context=min(context_window, 32000),
            system_reserve=800,
            response_reserve=2048,
            summary_max=1200,
            user_turn_max=2000,
            hot_buffer_pct=0.55,
        )


# ================================================================
# SECTION 2 — TOKEN ESTIMATOR
# ================================================================

class TokenEstimator:
    _CODE_BLOCK_RE = re.compile(r"```[\s\S]*?```")

    @classmethod
    def estimate(cls, text: str) -> int:
        if not text:
            return 0
        code_chars  = sum(len(m.group()) for m in cls._CODE_BLOCK_RE.finditer(text))
        prose_chars = len(text) - code_chars
        return int(prose_chars / 4.0) + int(code_chars / 3.2)

    @classmethod
    def estimate_messages(cls, msgs: List[BaseMessage]) -> int:
        return sum(cls.estimate(m.content) for m in msgs)


# ================================================================
# SECTION 3 — CONVERSATION TURN  ← NEW
# A single immutable record of one interview exchange.
# ================================================================

@dataclass(frozen=True)
class ConversationTurn:
    """
    Immutable record of one complete interview exchange.

    Fields
    ------
    turn_number  : 1-based index of this turn in the session
    question     : exact text received from the interviewer (post-preprocess)
    answer       : exact text generated by the LLM
    timestamp    : Unix time when the answer was generated
    tokens_sent  : estimated tokens in the context sent to the LLM
    tokens_recv  : estimated tokens in the response
    """
    turn_number:  int
    question:     str
    answer:       str
    timestamp:    float
    tokens_sent:  int = 0
    tokens_recv:  int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "turn":       self.turn_number,
            "question":   self.question,
            "answer":     self.answer,
            "timestamp":  self.timestamp,
            "tokens_sent": self.tokens_sent,
            "tokens_recv": self.tokens_recv,
        }

    def __str__(self) -> str:
        return (
            f"[Turn {self.turn_number}]\n"
            f"  Q: {self.question}\n"
            f"  A: {self.answer}\n"
        )


# ================================================================
# SECTION 4 — HYBRID MEMORY MANAGER  (unchanged)
# ================================================================

class HybridMemoryManager(BaseChatMessageHistory, BaseModel):
    messages:              List[BaseMessage] = Field(default_factory=list)
    moving_summary_buffer: str               = Field(default="")
    key_facts:             List[str]         = Field(default_factory=list)
    keep_last_n:           int               = Field(default=6)
    _dirty:                bool              = False

    llm:    Any = Field(default=None)
    budget: Any = Field(default=None)

    class Config:
        arbitrary_types_allowed = True

    _lock: threading.RLock = None  # type: ignore

    def model_post_init(self, __context: Any) -> None:
        object.__setattr__(self, '_lock', threading.RLock())
        object.__setattr__(self, '_dirty', False)

    def _msg_hash(self, msg: BaseMessage) -> str:
        return hashlib.md5(
            f"{type(msg).__name__}:{msg.content}".encode()
        ).hexdigest()[:12]

    def _token(self, text: str) -> int:
        return TokenEstimator.estimate(text)

    def _token_msgs(self, msgs: List[BaseMessage]) -> int:
        return TokenEstimator.estimate_messages(msgs)

    _FACT_PATTERNS = re.compile(
        r"(I (?:use|am using|work with|prefer|have)\b.{10,80}|"
        r"\d+\s*(?:k|K|ms|MB|GB|RPS|req|nodes?|cores?|workers?)\b.{0,40}|"
        r"(?:must|should|need to|required to)\s.{10,60}|"
        r"(?:the system|architecture|stack|language|framework)\s.{10,60})",
        re.IGNORECASE,
    )

    def _extract_facts(self, text: str) -> List[str]:
        found = []
        for m in self._FACT_PATTERNS.finditer(text):
            fact = m.group().strip().rstrip(".,;")
            if 10 < len(fact) < 120 and fact not in self.key_facts:
                found.append(fact)
        return found[:3]

    def add_messages(self, messages: List[BaseMessage]) -> None:
        with self._lock:
            existing_hashes = {self._msg_hash(m) for m in self.messages}
            added = False
            for msg in messages:
                if self._msg_hash(msg) in existing_hashes:
                    continue
                self.messages.append(msg)
                existing_hashes.add(self._msg_hash(msg))
                added = True
                if isinstance(msg, HumanMessage):
                    self.key_facts.extend(self._extract_facts(msg.content))
            if added:
                object.__setattr__(self, '_dirty', True)

    def clear(self) -> None:
        with self._lock:
            self.messages = []
            self.moving_summary_buffer = ""
            self.key_facts = []
            object.__setattr__(self, '_dirty', False)

    def soft_clear(self) -> None:
        with self._lock:
            keep = max(2, len(self.messages) // 2)
            self.messages = self.messages[-keep:]
            object.__setattr__(self, '_dirty', True)

    def _should_evict(self) -> bool:
        if self.budget is None:
            return len(self.messages) > self.keep_last_n * 2
        return self._token_msgs(self.messages) > self.budget.hot_budget

    def _evict_to_summary(self) -> None:
        if not self.llm:
            self.messages = self.messages[-(self.keep_last_n * 2):]
            return
        keep_count = self.keep_last_n * 2
        if len(self.messages) <= keep_count:
            return
        to_evict      = self.messages[:-keep_count]
        self.messages = self.messages[-keep_count:]
        new_summary   = self._call_summarizer(self.moving_summary_buffer, to_evict)
        if self.budget and self._token(new_summary) > self.budget.summary_max:
            words = new_summary.split()
            target_words = int(self.budget.summary_max * 3.5)
            new_summary = " ".join(words[:target_words]) + " [truncated]"
        self.moving_summary_buffer = new_summary
        object.__setattr__(self, '_dirty', False)

    def _call_summarizer(self, existing_summary: str, messages_to_summarize: List[BaseMessage]) -> str:
        lines = "\n".join(
            f"{'Human' if isinstance(m, HumanMessage) else 'AI'}: {m.content[:600]}"
            for m in messages_to_summarize
        )
        prompt = (
            "You are summarizing a technical interview conversation. "
            "Preserve ALL technical details: algorithms, data structures, "
            "system design decisions, code patterns, complexity analysis, "
            "and any constraints mentioned. Be concise but technically precise.\n\n"
            f"EXISTING SUMMARY:\n{existing_summary or '(none)'}\n\n"
            f"NEW CONVERSATION TURNS:\n{lines}\n\n"
            "UPDATED SUMMARY (max 200 words, dense technical facts only):"
        )
        try:
            resp = self.llm.invoke([HumanMessage(content=prompt)])
            return resp.content.strip()
        except Exception as e:
            logger.warning("Summarization failed, keeping existing: %s", e)
            return existing_summary

    def build_context(self, system_message: SystemMessage, current_human_msg: HumanMessage) -> List[BaseMessage]:
        with self._lock:
            if self._should_evict() and self._dirty:
                self._evict_to_summary()
            result: List[BaseMessage] = [system_message]
            if self.key_facts:
                unique_facts = list(dict.fromkeys(self.key_facts))[-12:]
                result.append(SystemMessage(
                    content="Key technical context:\n• " + "\n• ".join(unique_facts)
                ))
            if self.moving_summary_buffer.strip():
                result.append(SystemMessage(
                    content=f"[Earlier conversation summary]:\n{self.moving_summary_buffer.strip()}"
                ))
            result.extend(self.messages)
            result.append(current_human_msg)
            return result

    def get_stats(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "hot_messages":   len(self.messages),
                "hot_tokens":     self._token_msgs(self.messages),
                "summary_tokens": self._token(self.moving_summary_buffer),
                "key_facts_count": len(self.key_facts),
                "is_dirty":       self._dirty,
                "budget_hot_max": self.budget.hot_budget if self.budget else None,
            }


# ================================================================
# SECTION 5 — LLMController  (with conversation log)
# ================================================================

class LLMController(BaseLLMConfigurationInterface):

    def __init__(self, params: Dict[str, Any] = None, system_message: str = None):
        if params is None:
            params = {
                "max_tokens":  get_config().MAX_TOKENS,
                "temperature": get_config().TEMPERATURE,
            }
        BaseLLMConfigurationInterface.__init__(self, params)
        self.config = get_config()
        self.SYSTEM_MESSAGE = SystemMessage(
            content=system_message.strip() if system_message else ""
        )

        # Legacy compatibility — kept empty, never sent to LLM
        self.history: List[BaseMessage] = []

        self._memory: Optional[HybridMemoryManager] = None
        self._budget: Optional[TokenBudget] = None

        # ── Conversation log ─────────────────────────────────────────
        # Plain list of ConversationTurn objects.
        # Grows by 1 per generate_response() call.
        # Never pruned — it is the audit trail, not the LLM context.
        # Thread-safe: protected by _log_lock.
        self._conversation_log: List[ConversationTurn] = []
        self._log_lock = threading.Lock()

    # ────────────────────────────────────────────
    # setup()
    # ────────────────────────────────────────────

    def setup(self) -> bool:
        if self.config.LLM_MODE == LLMExecutionMode.REMOTE.value:
            self.mode = LLMExecutionMode.REMOTE.value
            self._setup_remote_provider()
        elif self.config.LLM_MODE == LLMExecutionMode.LOCAL.value:
            self.mode = LLMExecutionMode.LOCAL.value
            self._setup_local_provider()
        else:
            self._is_connected = False
            raise ValueError(f"Unknown execution mode: {self.config.LLM_MODE}")

        if self.mode == LLMExecutionMode.LOCAL.value:
            ctx = getattr(self.config, "CONTEXT_WINDOW", 8192)
            self._budget = TokenBudget.for_local(context_window=ctx)
        else:
            ctx = getattr(self.config, "CONTEXT_WINDOW", 128000)
            self._budget = TokenBudget.for_remote(context_window=ctx)

        keep_n = 4 if self.mode == LLMExecutionMode.LOCAL.value else 8
        self._memory = HybridMemoryManager(
            llm=self.client,
            budget=self._budget,
            keep_last_n=keep_n,
        )
        return self._is_connected

    def _setup_remote_provider(self):
        provider = self.config.LLM_PROVIDER
        if provider == LLMProvider.GEMINI.value:
            self.api_key  = self.config.GEMINI_API_KEY
            self.model_id = self.config.GEMINI_MODEL_ID
            self.client   = ChatGoogleGenerativeAI(
                model=self.model_id, temperature=self.temperature,
                max_tokens=self.max_tokens, api_key=self.api_key,
            )
        elif provider == LLMProvider.OPENAI.value:
            self.api_key  = self.config.OPENAI_API_KEY
            self.model_id = self.config.OPENAI_MODEL_ID
            self.base_url = self.config.OPEN_AI_BASE_URL
            self.client   = ChatOpenAI(
                model=self.model_id, temperature=self.temperature,
                max_tokens=self.max_tokens, api_key=self.api_key,
                base_url=self.base_url,
            )
        elif provider == LLMProvider.CLAUDE.value:
            self.api_key  = self.config.CLAUDE_API_KEY
            self.model_id = self.config.CLAUDE_MODEL_ID
            self.client   = ChatAnthropic(
                model=self.model_id, temperature=self.temperature,
                max_tokens=self.max_tokens, api_key=self.api_key,
            )
        elif provider == LLMProvider.COHERE.value:
            self.api_key  = self.config.COHERE_API_KEY
            self.model_id = self.config.COHERE_MODEL_ID
            self.client   = ChatCohere(
                model=self.model_id, temperature=self.temperature,
                max_tokens=self.max_tokens, cohere_api_key=self.api_key,
            )
        else:
            self._is_connected = False
            raise ValueError(f"Unknown provider: {self.config.LLM_PROVIDER}")
        self._is_connected = True

    def _setup_local_provider(self):
        ctx = getattr(self.config, "CONTEXT_WINDOW", 8192)
        self.api_key  = getattr(self.config, "OLLAMA_API_KEY", None)
        self.model_id = self.config.OLLAMA_MODEL_ID
        self.base_url = self.config.OLLAMA_BASE_URL
        self.client   = ChatOllama(
            model=self.model_id, base_url=self.base_url,
            temperature=self.temperature, num_predict=self.max_tokens,
            num_ctx=ctx,
        )
        self._is_connected = True

    # ────────────────────────────────────────────
    # Public helpers
    # ────────────────────────────────────────────

    def update_system_message(self, text: str):
        self.SYSTEM_MESSAGE = SystemMessage(content=text.strip())

    def _estimate_tokens(self, text: str) -> int:
        return TokenEstimator.estimate(text)

    def _count_tokens(self, messages: List[BaseMessage]) -> int:
        return TokenEstimator.estimate_messages(messages)

    # ────────────────────────────────────────────
    # Memory helpers
    # ────────────────────────────────────────────

    def _build_messages_from_memory(self, current_human_msg: Optional[HumanMessage] = None) -> List[BaseMessage]:
        if self._memory is None:
            return [self.SYSTEM_MESSAGE]
        if current_human_msg is None:
            return [self.SYSTEM_MESSAGE] + list(self._memory.messages)
        return self._memory.build_context(self.SYSTEM_MESSAGE, current_human_msg)

    def _save_turn_to_memory(self, user_input: str, ai_response: str):
        if self._memory is not None:
            self._memory.add_messages([
                HumanMessage(content=user_input.strip()),
                AIMessage(content=ai_response.strip()),
            ])

    def release_history(self):
        self.history = []
        if self._memory is not None:
            self._memory.clear()
        # NOTE: _conversation_log is NOT cleared here intentionally.
        # release_history() resets LLM context but preserves the audit log.
        # Call reset_log() explicitly if you also want the log cleared.

    # ────────────────────────────────────────────
    # Conversation log helpers  ← NEW
    # ────────────────────────────────────────────

    def _record_turn(self, question: str, answer: str, tokens_sent: int = 0) -> None:
        """Append a completed turn to the conversation log. Thread-safe."""
        with self._log_lock:
            turn = ConversationTurn(
                turn_number  = len(self._conversation_log) + 1,
                question     = question,
                answer       = answer,
                timestamp    = time.time(),
                tokens_sent  = tokens_sent,
                tokens_recv  = TokenEstimator.estimate(answer),
            )
            self._conversation_log.append(turn)

    def get_report(self) -> List[ConversationTurn]:
        """
        Returns the full ordered list of ConversationTurn objects
        for the current session.

        Usage
        -----
        turns = controller.get_report()
        for t in turns:
            print(t)                 # pretty print
            d = t.to_dict()          # dict for JSON / DB
        """
        with self._log_lock:
            return list(self._conversation_log)   # shallow copy, safe to iterate

    def get_report_as_dicts(self) -> List[Dict[str, Any]]:
        """
        Convenience method — returns list of plain dicts.
        Ready for json.dumps(), pandas.DataFrame(), or DB insert.

        Usage
        -----
        import json
        print(json.dumps(controller.get_report_as_dicts(), indent=2))
        """
        return [t.to_dict() for t in self.get_report()]

    def get_report_as_text(self) -> str:
        """
        Human-readable transcript of the full session.

        Usage
        -----
        print(controller.get_report_as_text())
        # or save to file:
        # with open("report.txt", "w") as f:
        #     f.write(controller.get_report_as_text())
        """
        turns = self.get_report()
        if not turns:
            return "No conversation recorded yet."

        lines = ["=" * 60, "INTERVIEW SESSION TRANSCRIPT", "=" * 60, ""]
        for t in turns:
            lines.append(f"[Turn {t.turn_number}]")
            lines.append(f"  Interviewer : {t.question}")
            lines.append(f"  Interviewee : {t.answer}")
            lines.append(f"  Tokens sent : {t.tokens_sent}  |  received : {t.tokens_recv}")
            lines.append("")
        lines.append("=" * 60)
        lines.append(f"Total turns  : {len(turns)}")
        lines.append(f"Total tokens sent    : {sum(t.tokens_sent for t in turns)}")
        lines.append(f"Total tokens received: {sum(t.tokens_recv for t in turns)}")
        lines.append("=" * 60)
        return "\n".join(lines)

    def reset_log(self) -> None:
        """
        Wipe the conversation log.
        Call this when starting a brand-new interview session
        (alongside release_history() to also reset LLM context).
        """
        with self._log_lock:
            self._conversation_log = []

    # ────────────────────────────────────────────
    # generate_response()
    # ────────────────────────────────────────────

    def generate_response(self, user_input: str) -> str:
        if not self._is_connected:
            raise ConnectionError("LLM Client is not connected. Call setup() first.")
        if not self.SYSTEM_MESSAGE or not self.SYSTEM_MESSAGE.content.strip():
            raise ValueError("System message is empty. Call update_system_message() first.")
        if not user_input.strip():
            raise ValueError("User input is empty.")

        human_message = HumanMessage(content=user_input.strip())

        if self._memory is not None:
            messages_to_send = self._memory.build_context(self.SYSTEM_MESSAGE, human_message)
            logger.debug("Memory stats: %s", self._memory.get_stats())
        else:
            messages_to_send = [self.SYSTEM_MESSAGE, human_message]

        tokens_sent = TokenEstimator.estimate_messages(messages_to_send)

        response = self._invoke_with_fallback(messages_to_send, human_message)

        if self._memory is not None:
            self._save_turn_to_memory(user_input, response.content)

        # ── Record to conversation log ────────────────────────────────
        self._record_turn(
            question    = user_input,
            answer      = response.content,
            tokens_sent = tokens_sent,
        )

        return response.content

    def _invoke_with_fallback(self, messages: List[BaseMessage], human_message: HumanMessage):
        try:
            return self.client.invoke(messages)
        except Exception as e:
            err = str(e).lower()
            if not ("context" in err or "exceed" in err or "token" in err
                    or "length" in err or "too long" in err):
                raise
            logger.warning("Context window hit — Level 1 fallback: %s", e)
            if self._memory is not None:
                self._memory.soft_clear()
                messages = self._memory.build_context(self.SYSTEM_MESSAGE, human_message)
            else:
                messages = [self.SYSTEM_MESSAGE, human_message]
            try:
                return self.client.invoke(messages)
            except Exception as e2:
                logger.warning("Level 1 failed — Level 2 fallback: %s", e2)
                if self._memory is not None:
                    self._memory.clear()
                return self.client.invoke([self.SYSTEM_MESSAGE, human_message])

    # ────────────────────────────────────────────
    # Async support
    # ────────────────────────────────────────────

    async def agenerate_response(self, user_input: str) -> str:
        if not self._is_connected:
            raise ConnectionError("LLM Client is not connected.")
        if not user_input.strip():
            raise ValueError("User input is empty.")

        human_message = HumanMessage(content=user_input.strip())

        if self._memory is not None:
            messages_to_send = self._memory.build_context(self.SYSTEM_MESSAGE, human_message)
        else:
            messages_to_send = [self.SYSTEM_MESSAGE, human_message]

        tokens_sent = TokenEstimator.estimate_messages(messages_to_send)
        response    = await self._ainvoke_with_fallback(messages_to_send, human_message)

        if self._memory is not None:
            self._save_turn_to_memory(user_input, response.content)

        self._record_turn(user_input, response.content, tokens_sent)
        return response.content

    async def _ainvoke_with_fallback(self, messages, human_message):
        try:
            return await self.client.ainvoke(messages)
        except Exception as e:
            err = str(e).lower()
            if not ("context" in err or "exceed" in err or "token" in err):
                raise
            if self._memory is not None:
                self._memory.soft_clear()
                messages = self._memory.build_context(self.SYSTEM_MESSAGE, human_message)
            return await self.client.ainvoke(messages)

    # ────────────────────────────────────────────
    # Streaming support
    # ────────────────────────────────────────────

    def stream_response(self, user_input: str):
        if not self._is_connected:
            raise ConnectionError("LLM not connected.")
        if not user_input.strip():
            raise ValueError("Empty input.")

        human_message = HumanMessage(content=user_input.strip())

        if self._memory is not None:
            messages_to_send = self._memory.build_context(self.SYSTEM_MESSAGE, human_message)
        else:
            messages_to_send = [self.SYSTEM_MESSAGE, human_message]

        tokens_sent   = TokenEstimator.estimate_messages(messages_to_send)
        full_response = []

        for chunk in self.client.stream(messages_to_send):
            text = chunk.content
            full_response.append(text)
            yield text

        if full_response:
            complete = "".join(full_response)
            if self._memory is not None:
                self._save_turn_to_memory(user_input, complete)
            self._record_turn(user_input, complete, tokens_sent)

    # ────────────────────────────────────────────
    # Cleanup
    # ────────────────────────────────────────────

    def cleanup(self):
        self.client         = None
        self.history        = []
        self._is_connected  = False
        self.SYSTEM_MESSAGE = None
        if self._memory is not None:
            self._memory.clear()
        self._memory = None
        # _conversation_log is intentionally kept alive after cleanup
        # so get_report() still works after the session ends.